Music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("main.urls")),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
        path("",views.music,name="music"),
        path("listen/<int:music_id>/",views.listen,name="listen"),
        path("musiclist/",views.music_url_list,name="url_list"),
        path("addmusic/",views.addmusic,name="addmusic"),
        ]

main/models.py
from django.db import models

class Music(models.Model):
    title = models.CharField(max_length=100)
    musician = models.CharField(max_length=100)
    image = models.ImageField(upload_to="music_image")
    date = models.DateTimeField(auto_now_add=True)
    music_file = models.FileField(upload_to="music")

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from .models import Music


class AddMusicForm(forms.ModelForm):
    class Meta:
        model = Music
        fields = ["title","musician","image","music_file"]
        widgets = {
                'title': forms.TextInput(attrs={
                    "name":"title",
                    "placeholder":"Title",
                    "type":"text",
                    "class":"form-control my-2",
                    }),

                'musician': forms.TextInput(attrs={
                    "name":"musician",
                    "placeholder":"Musician",
                    "type":"text",
                    "class":"form-control my-2",
                    }),
                }


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields["image"].widget = forms.FileInput(attrs={
            "name":"image",
            "type":"file",
            "class":"form-control my-2"
            })

        self.fields["music_file"].widget = forms.FileInput(attrs={
            "name":"musicfile",
            "type":"file",
            "class":"form-control my-2"
            })

main/views.py
from django.shortcuts import render,redirect
from .models import Music
from django.http import HttpRequest,JsonResponse
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize
from .forms import AddMusicForm


def music(request:HttpRequest):
    if request.method == "POST":
        search = request.POST.get("search")
        musics = Music.objects.filter(
                title__icontains=search)
    else:
        musics = Music.objects.all()

    context = {
            "musics":musics,
            }
    return render(request,"music.html",context)



def listen(request:HttpRequest,music_id:int):
    music = Music.objects.get(id=music_id)

    context = {
            "music":music,
            }
    return render(request,"listen.html",context)


@csrf_exempt
def music_url_list(request:HttpRequest):
    if request.method == "POST":
        music_url = request.POST.get("music_url")
        status = request.POST.get("status")
        count = request.POST.get("count")

        current_music = Music.objects.get(music_file=music_url)

        if status == "next":
            next_music_id = current_music.id + int(count)
            try:
                music = Music.objects.get(id=next_music_id)
            except Music.DoesNotExist:
                music = current_music
                end = True

        elif status == "previous":
            previous_music_id = current_music.id + int(count)
            try:
                music = Music.objects.get(id=previous_music_id)
            except Music.DoesNotExist:
                music = current_music
                end = True

        music_data = {
                "id": music.id,
                "title": music.title,
                "musician":music.musician,
                "image": music.image.url,
                "music_url": music.music_file.url,
                "end": end,
                }


        return JsonResponse(music_data)



def addmusic(request:HttpRequest):
    if request.method == "POST":
        form = AddMusicForm(request.POST,request.FILES)

        if form.is_valid():
            form.save()
            return redirect("main:music")
    else:
        form = AddMusicForm()


    return render(request,"addmusic.html",{"form":form})

templates/addmusic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <style>
    body {
      background: #000;
      color: #fff;
      justify-content: center;
      align-content: center;
    }
  </style>
</head>
<body>
  <div class="container">
    <h2 class="fw-3 text-center mt-3">Upload Music</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <div class="row d-grid mx-1">
      <button class="btn btn-primary my-3"> Save </button>
      </div>
    </form>
  </div>
</body>
</html>

templates/listen.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <style>
    body {
      background: #000;
    }
    img {
      height: 300px;
      width: 300px;
      border-radius: 150px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h2 class="text-light text-center my-3">Listening To</h2>
    <h5 class="text-center text-light my-1 music_name">{{music.title}}</h5>
    <p class="text-center text-light musician">
      {{music.musician}}
    </p>
  </div>
  <div class="image text-center">
    <img src="{{music.image.url}}" alt="" id="music_image">
  </div>


  <div class="container mt-5 clearfix">
    <div class="audio-player text-center float-center">
      <audio id="audio" controls autoplay loop data-url="{{music.music_file}}">
        <source src="{{music.music_file.url}}" type="audio/mp3" id="file_path">
        Your browser does not support the audio element.
      </audio>
    </div>
  </div>

  <div class="row justify-content-around align-items-center mt-3">
    <div class="col-4 text-center">
      <button class="btn border-light" id="previous"><i class="fas fa-backward text-light"></i></button>
    </div>
    <div class="col-4 text-center">
      <button class="btn border-light" id="next"><i class="fas fa-forward text-light"></i></button>
    </div>
  </div>
  <script src="{% static 'js/index.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
    const next = document.querySelector("#next");
    const previous = document.querySelector("#previous");
    let music_name = document.querySelector(".music_name");
    let musician = document.querySelector(".musician");
    let audio = document.querySelector("audio");
    let file_path = document.querySelector("#file_path");
    let music_image = document.querySelector("#music_image");
    let audio_url = audio.getAttribute("data-url");
    
    let count = 0;
    
    next.addEventListener("click", () => {
      count++;
      let myData = {
        status: "next",
        music_url: audio_url,
        count: count,
      };

      $.ajax({
        url: "{% url 'main:url_list' %}",
        method: "POST",
        data: myData,
        success: function (data) {
          music_name.innerHTML = `${data.title}`;
          music_image.setAttribute("src", `${data.image}`);
          musician.innerHTML = `${data.musician}`;
          file_path.setAttribute("src", `${data.music_url}`);
          audio.pause()
          audio.load();
        }
      })
    });
    
    
    previous.addEventListener("click",() => {
      count--;
      let myData = {
        status: "previous",
        music_url: audio_url,
        count: count,
      };
      $.ajax({
        url: "{% url 'main:url_list' %}",
        method: "POST",
        data: myData,
        success: function (data) {
          music_name.innerHTML = `${data.title}`;
          music_image.setAttribute("src", `${data.image}`);
          musician.innerHTML = `${data.musician}`;
          file_path.setAttribute("src", `${data.music_url}`);
          audio.pause()
          audio.load();
        }
      })
    });
  </script>
</body>
</html>

templates/music.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <style>
    body {
      background: #000;
    }
    a {
      text-decoration: none;
    }
    .music_name {
      border: hsl(0 ,0%,70%) 0 0 10px;
    }
  </style>
</head>
<body>
  <h2 class="text-center text-light m-3">All Musics</h2>
  <div class="container float-start">
    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-10">
          <input type="search" class="form-control" name="search" placeholder="search">
        </div>
        <div class="col-2">
          <button class="btn bg-primary btn-ouline-primary text-light"><i class="fas fa-search"></i></button>
        </div>
      </div>
    </form>
  </div>
  <div class="container">
    <div class="row">
      <div class="col my-2">
          <a href="{% url 'main:addmusic' %}"><button class="btn btn-primary btn-ouline-danger text-light">Add Music</button>
          </a>
      </div>
    </div>
    </div>
  <div class="container mt-5">
    {% for music in musics %}
    <a href="{% url 'main:listen' music.id %}">
      <div class="row my-4 music_name bg-gradient">
        <div class="col-12 p-2">
          <h4 class="text-light">{{music.title}}</h4>
          <p class="text-light float-start">
            {{music.musician}}
          </p>
          <p class="float-end">
            {{music.date}}
          </p>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>